### ISSUE TITLE
What is the create_data_stream in the notebook

### ISSUE THREAD

**Issue by BoonthichaSaejia** [ngoquanghuy99/summarization-transformer-gpt2#1]
I try to follow your code but it seems like the create_data_stream function is missing. Would you mind updating your notebook or show the code for this function?

**Comment by ngoquanghuy99** [comment]
No, i think it isn't. You might miss something.

**Comment by BoonthichaSaejia** [comment]
sorry, I really missed it. Thank you for your answer and notebook

**Comment by ngoquanghuy99** [comment]
Happy to help!
