### ISSUE TITLE
Stops early in training 

### ISSUE THREAD

**Issue by alradulo** [ngoquanghuy99/summarization-transformer-gpt2#2]
Training fails every time.  The partially generated model also produces ODD results (see bellow the error)

```

Step   3500: Ran 100 train steps in 40.21 secs
Step   3500: train WeightedCategoryCrossEntropy |  6.82346439
Step   3500: eval  WeightedCategoryCrossEntropy |  7.05117989
Step   3500: eval      WeightedCategoryAccuracy |  0.09183674
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
<ipython-input-71-f6c94a485f0a> in <module>()
      1 get_ipython().system('rm -f /content/drive/MyDrive/Summarization/models/model.pkl.gz')
      2 loop = training_loop(TransformerLM, train_batch_stream, eval_batch_stream, output_dir='/content/drive/MyDrive/Summarization/models')
----> 3 loop.run(10000)

2 frames
/usr/local/lib/python3.7/dist-packages/trax/supervised/training.py in run(self, n_steps)
    433           loss_acc, step_acc = 0.0, 0
    434 
--> 435         loss, optimizer_metrics = self._run_one_step(task_index, task_changed)
    436 
    437         # optimizer_metrics and loss are replicated on self.n_devices, a few

/usr/local/lib/python3.7/dist-packages/trax/supervised/training.py in _run_one_step(self, task_index, task_changed)
    623 
    624     learning_rate = self._tasks[task_index].learning_rate(step)
--> 625     batch = self._tasks[task_index].next_batch()
    626     rng = self.new_rng()
    627     trainer = self._trainer_per_task[task_index]

/usr/local/lib/python3.7/dist-packages/trax/supervised/training.py in next_batch(self)
   1099   def next_batch(self):
   1100     """Returns one batch of labeled data: a tuple of input(s) plus label."""
-> 1101     return next(self._labeled_data)
   1102 
   1103   @property

StopIteration: 

------------------------------------------------

It was a sunny day when I went to the market to buy some flowers. But
I only found roses, not tulips. 

&#
&#39
&#39;
&#39;<EOS>
&#39;<EOS>

```

8:37 AM
[1]
from google.colab import drive
drive.mount('/content/drive')
Mounted at /content/drive
8:37 AM
[2]
!pip -q install trax
     |████████████████████████████████| 624kB 13.5MB/s 
     |████████████████████████████████| 153kB 29.2MB/s 
     |████████████████████████████████| 3.4MB 19.1MB/s 
     |████████████████████████████████| 368kB 55.2MB/s 
     |████████████████████████████████| 3.9MB 50.6MB/s 
     |████████████████████████████████| 256kB 56.2MB/s 
     |████████████████████████████████| 2.1MB 21.8MB/s 
     |████████████████████████████████| 1.2MB 50.7MB/s 
     |████████████████████████████████| 61kB 8.7MB/s 
     |████████████████████████████████| 3.3MB 46.0MB/s 
     |████████████████████████████████| 901kB 45.5MB/s 
8:38 AM
[3]
import sys
import os
8:38 AM
[4]
def tokenize(input_str, EOS=1):
    """Input str to features dict, ready for inference"""
8:38 AM
[5]
# test 
print(tokenize('why you did that shit to me, man?', EOS=1))
[11406, 33, 206, 285, 12803, 320, 156, 2, 157, 3882, 1]
8:38 AM
[6]
def DotProductAttention(query, key, value, mask):
    """Dot product self-attention.
8:38 AM
[7]
def compute_attention_heads_closure(n_heads, d_head):
    """ Function that simulates environment inside CausalAttention function.
8:38 AM
[8]
def dot_product_self_attention(q, k, v):
    """ Masked dot product self attention.
8:38 AM
[9]
def compute_attention_output_closure(n_heads, d_head):
    """ Function that simulates environment inside CausalAttention function.
8:38 AM
[10]
def CausalAttention(d_feature, 
                    n_heads, 
8:38 AM
[11]
# Take a look at the causal attention model
print(CausalAttention(d_feature=512, n_heads=8))
Serial[
  Branch_out3[
    [Dense_512, AttnHeads]
    [Dense_512, AttnHeads]
    [Dense_512, AttnHeads]
  ]
  DotProductAttn_in3
  AttnOutput
  Dense_512
]
8:38 AM
[12]
def DecoderBlock(d_model, d_ff, n_heads,
                 dropout, mode, ff_activation):
8:38 AM
[13]
# Take a look at the decoder block
print(DecoderBlock(d_model=512, d_ff=2048, n_heads=8, dropout=0.1, mode='train', ff_activation=tl.Relu))
[Serial[
  Branch_out2[
    None
    Serial[
      LayerNorm
      Serial[
        Branch_out3[
          [Dense_512, AttnHeads]
          [Dense_512, AttnHeads]
          [Dense_512, AttnHeads]
        ]
        DotProductAttn_in3
        AttnOutput
        Dense_512
      ]
      Dropout
    ]
  ]
  Add_in2
], Serial[
  Branch_out2[
    None
    Serial[
      LayerNorm
      Dense_2048
      Serial[
        Relu
      ]
      Dropout
      Dense_512
      Dropout
    ]
  ]
  Add_in2
]]
8:38 AM
[14]
def TransformerLM(vocab_size=33300,
                  d_model=512,
8:38 AM
[15]
# Take a look at the Transformer
print(TransformerLM(n_layers=1))
Serial[
  Serial[
    ShiftRight(1)
  ]
  Embedding_33300_512
  Dropout
  PositionalEncoding
  Serial[
    Branch_out2[
      None
      Serial[
        LayerNorm
        Serial[
          Branch_out3[
            [Dense_512, AttnHeads]
            [Dense_512, AttnHeads]
            [Dense_512, AttnHeads]
          ]
          DotProductAttn_in3
          AttnOutput
          Dense_512
        ]
        Dropout
      ]
    ]
    Add_in2
  ]
  Serial[
    Branch_out2[
      None
      Serial[
        LayerNorm
        Dense_2048
        Serial[
          Relu
        ]
        Dropout
        Dense_512
        Dropout
      ]
    ]
    Add_in2
  ]
  LayerNorm
  Dense_33300
  LogSoftmax
]
8:39 AM
[16]
# Test it out!
sentence_test_nxt_symbl = "I want to fly in the sky."
8:39 AM
[16]
 
8:38 AM
[16]
# Get the model architecture
model = TransformerLM(mode='eval')
It was a sunny day when I went to the market to buy some flowers. But
I only found roses, not tulips. 

[9207]
[9207, 1725]
[9207, 1725, 1628]
[9207, 1725, 1628, 1]
&#39;<EOS>
It’s the posing craze sweeping the U.S. after being brought to fame by
skier Lindsey Vonn, soccer star Omar Cummings, baseball player Albert
Pujols - and even Republican politician Rick Perry. But now four
students at Riverhead High School on Long Island, New York, have been
suspended for dropping to a knee and taking up a prayer pose to mimic
Denver Broncos quarterback Tim Tebow. Jordan Fulcoly, Wayne Drexel,
Tyler Carroll and Connor Carroll were all suspended for one day
because the ‘Tebowing’ craze was blocking the hallway and presenting a
safety hazard to students. Scroll down for video. Banned: Jordan
Fulcoly, Wayne Drexel, Tyler Carroll and Connor Carroll (all pictured
left) were all suspended for one day by Riverhead High School on Long
Island, New York, for their tribute to Broncos quarterback Tim Tebow.
Issue: Four of the pupils were suspended for one day because they
allegedly did not heed to warnings that the 'Tebowing' craze at the
school was blocking the hallway and presenting a safety hazard to
students. 

[9207]
[9207, 1725]
[9207, 1725, 1628]
[9207, 1725, 1628, 1]
&#39;<EOS>
8:39 AM
[17]
# Test it out!
sentence_test_nxt_symbl = "I want to fly in the sky."
8:39 AM
[18]
def greedy_decode(input_sentence, model):
    """Greedy decode function.
8:39 AM
[19]
# Test it out on a sentence!
test_sentence = "It was a sunny day when I went to the market to buy some flowers. But I only found roses, not tulips."
It was a sunny day when I went to the market to buy some flowers. But
I only found roses, not tulips. 

&#
&#39
&#39;
&#39;<EOS>
&#39;<EOS>
8:39 AM
[20]
# Test it out with a whole article!
article = "It’s the posing craze sweeping the U.S. after being brought to fame by skier Lindsey Vonn, soccer star Omar Cummings, baseball player Albert Pujols - and even Republican politician Rick Perry. But now four students at Riverhead High School on Long Island, New York, have been suspended for dropping to a knee and taking up a prayer pose to mimic Denver Broncos quarterback Tim Tebow. Jordan Fulcoly, Wayne Drexel, Tyler Carroll and Connor Carroll were all suspended for one day because the ‘Tebowing’ craze was blocking the hallway and presenting a safety hazard to students. Scroll down for video. Banned: Jordan Fulcoly, Wayne Drexel, Tyler Carroll and Connor Carroll (all pictured left) were all suspended for one day by Riverhead High School on Long Island, New York, for their tribute to Broncos quarterback Tim Tebow. Issue: Four of the pupils were suspended for one day because they allegedly did not heed to warnings that the 'Tebowing' craze at the school was blocking the hallway and presenting a safety hazard to students."
It’s the posing craze sweeping the U.S. after being brought to fame by
skier Lindsey Vonn, soccer star Omar Cummings, baseball player Albert
Pujols - and even Republican politician Rick Perry. But now four
students at Riverhead High School on Long Island, New York, have been
suspended for dropping to a knee and taking up a prayer pose to mimic
Denver Broncos quarterback Tim Tebow. Jordan Fulcoly, Wayne Drexel,
Tyler Carroll and Connor Carroll were all suspended for one day
because the ‘Tebowing’ craze was blocking the hallway and presenting a
safety hazard to students. Scroll down for video. Banned: Jordan
Fulcoly, Wayne Drexel, Tyler Carroll and Connor Carroll (all pictured
left) were all suspended for one day by Riverhead High School on Long
Island, New York, for their tribute to Broncos quarterback Tim Tebow.
Issue: Four of the pupils were suspended for one day because they
allegedly did not heed to warnings that the 'Tebowing' craze at the
school was blocking the hallway and presenting a safety hazard to
students. 

&#
&#39
&#39;
&#39;<EOS>
&#39;<EOS>
[ ]
Type code here to execute.

check
2scompleted at 8:39 AM

**Comment by ngoquanghuy99** [comment]
Hi @alradulo 
I don't know how to address this issue as well. 
I already created an issue in the official repository of Trax framework and I hasn't received any answer yet.
This kind of framework is just for fun, it should not be our main framework. Try using PyTorch instead, or at least Tensorflow.
